config/routes.rb
Rails.application.routes.draw do
  
  post '/rate' => 'rater#create', :as => 'rate'

  devise_for :users
  get 'users' => 'users#user'
  resources :movies do
    resources :reviews
  end 
  root "movies#index"
  
  resources :conversations do
    resources :messages
  end 

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
	belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :recipient_id

	scope :involving, -> (user) do
		where("conversations.sender_id =? OR conversations.recipient_id =?", user_id, user_id)
	end
	scope :between, -> (sender_id, recipient_id) do
		where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", 
			sender_id,recipient_id, recipient_id, sender_id)
	end 
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  searchkick
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :reviews, dependent: :destroy
  has_many :ratings, dependent: :destroy
  #ratyrate_rateable :movie_rating

  def all_ratings
  	ratings.pluck(:rating)
  end

  def get_rating_for_review(review)
    user = ratings.find_by(user_id: review.user_id)
    if user
      user.rating
    else

    end  
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews, dependent: :destroy

  has_many :ratings, dependent: :destroy
  has_many :conversations, foreign_key: :sender_id

  scope :all_except_current_user, -> (current_user){  where("id != ?", current_user.id) }

  #ratyrate_rater


  def commented?(movie)
    ratings.find_by(movie_id: movie.id)
  	
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	before_action :find_movie, only: [:edit, :show, :update]
	def new
		@movie = Movie.new
	end

	def edit
		
	end

	def create
		@movie = Movie.new(movie_params)
		if @movie.save 
			redirect_to @movie, notice: "Successfully created the movie"
		else
		    render 'new' 
		end 
	end

	def destroy
		
	end

	def update
		if @movie.update(movie_params)
			redirect_to @movie, notice: "Successfully updated the movie"
		else
		  render 'edit'
		end   

	end

	def index
	  if params[:search]
	  	@movies = Movie.search params[:search]
	  else 
	    @movies = Movie.all
	  end

	end

	def show
	  rating_array = @movie.all_ratings
	  @rating_avg = rating_avg(rating_array)
	  @reviews = @movie.reviews
	  puts "Reviews size ***********: #{@reviews.size}***************"
	end
    
    def search_movie
    	
    end
	private

	def rating_avg(rating_array)
		rating_array.inject(0.0){ |sum, el| sum + el }.to_f / rating_array.size
		
	end

	def find_movie
		@movie = Movie.find(params[:id])
		
	end

	def movie_params
		params.require(:movie).permit(:title, :description, :rating, :director, :image)
	end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_movie


	def new
		#@review = current_user.reviews.build
		
		#@review = @movie.reviews.new
	end

	def create
		
		@review = @movie.reviews.new(review_params)
		@review.user = current_user
		rating_temp = @movie.ratings.new
		rating_temp.user = current_user
		rating_temp.rating = params[:score]
		
		if @review.save && rating_temp.save
			redirect_to :back, notice: "Review added successfully !"
		else 
			render :back
		end 
	end


	private 

	def set_movie
		@movie = Movie.find(params[:movie_id])
	end

	def review_params
		params.require(:review).permit(:review_text)
	end

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def user
		@users = User.all_except_current_user(current_user)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
	def self_or_other(message)
		message.user == current_user ? "self" : "other"
	end
	
	def message_interlocutor(message)
		message.user == message.conversation.sender ? message.conversation.sender : message.conversation.recipient
	end 
end

app/helpers/movies_helper.rb
module MoviesHelper
	def current_user_commented?(movie)
		current_user.commented?(movie)
		
	end

	def rating_wrt_review(movie,review)
	  movie.get_rating_for_review(review)
	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
 <% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-static-top navbar-custom" role="navigation">

 <div class = "container"> 
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <%= link_to "MovieReview", root_path, class: "navbar-brand" %>
  </div>

  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= form_tag movies_path, method: :get, class: "navbar-form navbar-left" do %>
          <%= text_field_tag :search, params[:search], :id => 'search_field', class: "form-control" %>
          <%= submit_tag "Search", :name => nil, class: "btn" %> 
          
        <% end %> 
                <!--<form class="navbar-form navbar-left">
                  <input type="text" class="form-control">
                  <button type="submit" class="btn">Search</button>
                </form> -->
              </li>
              <% if !current_user %>
              <li>

                <%= link_to "Sign In", new_user_session_path %>
              </li>
              <li>
                <%= link_to "Sign up", new_user_registration_path %>
              </li>
              <% end %>

              <% if user_signed_in? %>
              <li>
                <%= link_to "New Movie", new_movie_path %>

              </li>
              <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: 'delete' %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->

        </div>
      </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class = "full">
<head>
	<title>MovieReview</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
	 <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %> 
	<%= csrf_meta_tags %>
</head>

<%= render "layouts/shim" %>
<body>

	<%= render "layouts/header" %>
	<div class = "container">
		<div class = "row">


		<%= yield %>
		</div>

		<%= debug(params) if Rails.env.development? %>
</body>
    </div>
</html>